/**
 * Parity with Woodshed's chord model (fixtures/woodshed.json, regenerated by
 * scripts/export-woodshed-fixtures.py). Agreement is on root and family.
 *
 * Intentional divergences are listed below: each is a pitch-class set with
 * two honest readings, where this engine prefers the one with the root in the
 * bass (or Woodshed departs from the chord the fixture was built as). For
 * those, both readings must still be offered and flagged ambiguous.
 */

import { describe, expect, it } from 'vitest';
import fixtures from '../fixtures/woodshed.json';
import { detectChord } from './detect';
import { noteToPc } from './pitch';

type Fixture = {
  midi: number[];
  intended: { root_pc: number; quality: string; family: string };
  position: string;
  woodshed: {
    root: string;
    quality: string;
    family: string;
    root_inferred: boolean;
    ambiguous: boolean;
  } | null;
};

const DIVERGENCES = new Set([
  'm7b5/first-inversion', // Cø/Eb = Ebm6
  '6/first-inversion', // C6/E = Am7/E
  'm6/root', // Cm6 = Aø/C
  'm6/first-inversion', // Cm6/Eb = Aø/Eb
  '9/first-inversion', // C9/E ≈ Em7b5(b13)
  'm9/first-inversion', // Cm9/Eb ≈ EbMaj7(13)
  '7b9/first-inversion', // C7b9/E ≈ Edim7(b13)
]);

const all = fixtures as Fixture[];
const sameChord = (a: { rootPc: number; family: string }, b: { rootPc: number; family: string }) =>
  a.rootPc === b.rootPc && a.family === b.family;

describe('Woodshed parity', () => {
  it('covers every Woodshed template on every root', () => {
    expect(all.length).toBe(588);
  });

  it.each(
    all.map((f) => [`${f.intended.quality}/${f.position} on ${f.intended.root_pc}`, f] as const),
  )('%s', (_, fixture) => {
    const detection = detectChord(fixture.midi);
    const readings = detection.readings.map((r) => ({ rootPc: r.rootPc, family: r.family }));
    expect(fixture.woodshed).not.toBeNull();
    const woodshed = { rootPc: noteToPc(fixture.woodshed!.root), family: fixture.woodshed!.family };
    const intended = { rootPc: fixture.intended.root_pc, family: fixture.intended.family };

    expect(readings.some((r) => sameChord(r, intended))).toBe(true);
    if (DIVERGENCES.has(`${fixture.intended.quality}/${fixture.position}`)) {
      expect(readings.some((r) => sameChord(r, woodshed))).toBe(true);
      expect(detection.ambiguous).toBe(true);
    } else {
      expect(readings[0]).toEqual(woodshed);
    }
  });
});
